[package]
name = "miao-native"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "miao-run"
path = "src/bin/miao-run.rs"

[dependencies]
napi = { version = "2", default-features = false, features = ["napi6"] }
napi-derive = "2"
similar = "2"
regex = "1"
memchr = "2"
gix = { version = "0.88", default-features = false, features = ["status", "revision", "blob-diff", "sha1"] }

[build-dependencies]
napi-build = "2"

[target.'cfg(target_os = "linux")'.dependencies]
landlock = "0.4"

[profile.release]
lto = true
