// Generated by @miao/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.capabilities"]["capabilities.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.capabilities"]) => (input?: Endpoint1_0Input) =>
  raw["capabilities.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.capabilities"]) => ({ get: Endpoint1_0(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.formatter"]["formatter.status"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.formatter"]) => (input?: Endpoint2_0Input) =>
  raw["formatter.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.formatter"]) => ({ status: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.config"]["config.get"]>[0]
type Endpoint3_0Input = { readonly location?: Endpoint3_0Request["query"]["location"] }
const Endpoint3_0 = (raw: RawClient["server.config"]) => (input?: Endpoint3_0Input) =>
  raw["config.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_1Request = Parameters<RawClient["server.config"]["config.providers"]>[0]
type Endpoint3_1Input = { readonly location?: Endpoint3_1Request["query"]["location"] }
const Endpoint3_1 = (raw: RawClient["server.config"]) => (input?: Endpoint3_1Input) =>
  raw["config.providers"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_2Request = Parameters<RawClient["server.config"]["config.catalog"]>[0]
type Endpoint3_2Input = { readonly location?: Endpoint3_2Request["query"]["location"] }
const Endpoint3_2 = (raw: RawClient["server.config"]) => (input?: Endpoint3_2Input) =>
  raw["config.catalog"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup3 = (raw: RawClient["server.config"]) => ({
  get: Endpoint3_0(raw),
  providers: Endpoint3_1(raw),
  catalog: Endpoint3_2(raw),
})

type Endpoint4_0Request = Parameters<RawClient["server.lsp"]["lsp.status"]>[0]
type Endpoint4_0Input = { readonly location?: Endpoint4_0Request["query"]["location"] }
const Endpoint4_0 = (raw: RawClient["server.lsp"]) => (input?: Endpoint4_0Input) =>
  raw["lsp.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup4 = (raw: RawClient["server.lsp"]) => ({ status: Endpoint4_0(raw) })

type Endpoint5_0Request = Parameters<RawClient["server.mcp"]["mcp.status"]>[0]
type Endpoint5_0Input = { readonly location?: Endpoint5_0Request["query"]["location"] }
const Endpoint5_0 = (raw: RawClient["server.mcp"]) => (input?: Endpoint5_0Input) =>
  raw["mcp.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint5_1Request = Parameters<RawClient["server.mcp"]["mcp.connect"]>[0]
type Endpoint5_1Input = {
  readonly name: Endpoint5_1Request["params"]["name"]
  readonly location?: Endpoint5_1Request["query"]["location"]
}
const Endpoint5_1 = (raw: RawClient["server.mcp"]) => (input: Endpoint5_1Input) =>
  raw["mcp.connect"]({ params: { name: input["name"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint5_2Request = Parameters<RawClient["server.mcp"]["mcp.disconnect"]>[0]
type Endpoint5_2Input = {
  readonly name: Endpoint5_2Request["params"]["name"]
  readonly location?: Endpoint5_2Request["query"]["location"]
}
const Endpoint5_2 = (raw: RawClient["server.mcp"]) => (input: Endpoint5_2Input) =>
  raw["mcp.disconnect"]({ params: { name: input["name"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint5_3Request = Parameters<RawClient["server.mcp"]["mcp.resources"]>[0]
type Endpoint5_3Input = { readonly location?: Endpoint5_3Request["query"]["location"] }
const Endpoint5_3 = (raw: RawClient["server.mcp"]) => (input?: Endpoint5_3Input) =>
  raw["mcp.resources"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.mcp"]) => ({
  status: Endpoint5_0(raw),
  connect: Endpoint5_1(raw),
  disconnect: Endpoint5_2(raw),
  resources: Endpoint5_3(raw),
})

type Endpoint6_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint6_0Input = { readonly location?: Endpoint6_0Request["query"]["location"] }
const Endpoint6_0 = (raw: RawClient["server.location"]) => (input?: Endpoint6_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup6 = (raw: RawClient["server.location"]) => ({ get: Endpoint6_0(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint7_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup7 = (raw: RawClient["server.agent"]) => ({ list: Endpoint7_0(raw) })

type Endpoint8_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint8_0Input = {
  readonly workspace?: Endpoint8_0Request["query"]["workspace"]
  readonly limit?: Endpoint8_0Request["query"]["limit"]
  readonly order?: Endpoint8_0Request["query"]["order"]
  readonly search?: Endpoint8_0Request["query"]["search"]
  readonly directory?: Endpoint8_0Request["query"]["directory"]
  readonly project?: Endpoint8_0Request["query"]["project"]
  readonly subpath?: Endpoint8_0Request["query"]["subpath"]
  readonly cursor?: Endpoint8_0Request["query"]["cursor"]
}
const Endpoint8_0 = (raw: RawClient["server.session"]) => (input?: Endpoint8_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint8_1Input = {
  readonly id?: Endpoint8_1Request["payload"]["id"]
  readonly agent?: Endpoint8_1Request["payload"]["agent"]
  readonly model?: Endpoint8_1Request["payload"]["model"]
  readonly location?: Endpoint8_1Request["payload"]["location"]
}
const Endpoint8_1 = (raw: RawClient["server.session"]) => (input?: Endpoint8_1Input) =>
  raw["session.create"]({
    payload: { id: input?.["id"], agent: input?.["agent"], model: input?.["model"], location: input?.["location"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint8_2 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint8_3Input = { readonly sessionID: Endpoint8_3Request["params"]["sessionID"] }
const Endpoint8_3 = (raw: RawClient["server.session"]) => (input: Endpoint8_3Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_4Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint8_4Input = {
  readonly sessionID: Endpoint8_4Request["params"]["sessionID"]
  readonly agent: Endpoint8_4Request["payload"]["agent"]
}
const Endpoint8_4 = (raw: RawClient["server.session"]) => (input: Endpoint8_4Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint8_5Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint8_5Input = {
  readonly sessionID: Endpoint8_5Request["params"]["sessionID"]
  readonly model: Endpoint8_5Request["payload"]["model"]
}
const Endpoint8_5 = (raw: RawClient["server.session"]) => (input: Endpoint8_5Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint8_6Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint8_6Input = {
  readonly sessionID: Endpoint8_6Request["params"]["sessionID"]
  readonly id?: Endpoint8_6Request["payload"]["id"]
  readonly prompt: Endpoint8_6Request["payload"]["prompt"]
  readonly delivery?: Endpoint8_6Request["payload"]["delivery"]
  readonly resume?: Endpoint8_6Request["payload"]["resume"]
}
const Endpoint8_6 = (raw: RawClient["server.session"]) => (input: Endpoint8_6Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: { id: input["id"], prompt: input["prompt"], delivery: input["delivery"], resume: input["resume"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_7Request = Parameters<RawClient["server.session"]["session.skill"]>[0]
type Endpoint8_7Input = {
  readonly sessionID: Endpoint8_7Request["params"]["sessionID"]
  readonly skill: Endpoint8_7Request["payload"]["skill"]
  readonly resume?: Endpoint8_7Request["payload"]["resume"]
}
const Endpoint8_7 = (raw: RawClient["server.session"]) => (input: Endpoint8_7Input) =>
  raw["session.skill"]({
    params: { sessionID: input["sessionID"] },
    payload: { skill: input["skill"], resume: input["resume"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_8Request = Parameters<RawClient["server.session"]["session.shell"]>[0]
type Endpoint8_8Input = {
  readonly sessionID: Endpoint8_8Request["params"]["sessionID"]
  readonly command: Endpoint8_8Request["payload"]["command"]
  readonly resume?: Endpoint8_8Request["payload"]["resume"]
}
const Endpoint8_8 = (raw: RawClient["server.session"]) => (input: Endpoint8_8Input) =>
  raw["session.shell"]({
    params: { sessionID: input["sessionID"] },
    payload: { command: input["command"], resume: input["resume"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_9Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint8_9Input = { readonly sessionID: Endpoint8_9Request["params"]["sessionID"] }
const Endpoint8_9 = (raw: RawClient["server.session"]) => (input: Endpoint8_9Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_10Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint8_10Input = { readonly sessionID: Endpoint8_10Request["params"]["sessionID"] }
const Endpoint8_10 = (raw: RawClient["server.session"]) => (input: Endpoint8_10Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_11Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint8_11Input = {
  readonly sessionID: Endpoint8_11Request["params"]["sessionID"]
  readonly messageID: Endpoint8_11Request["payload"]["messageID"]
  readonly files?: Endpoint8_11Request["payload"]["files"]
}
const Endpoint8_11 = (raw: RawClient["server.session"]) => (input: Endpoint8_11Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_12Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint8_12Input = { readonly sessionID: Endpoint8_12Request["params"]["sessionID"] }
const Endpoint8_12 = (raw: RawClient["server.session"]) => (input: Endpoint8_12Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_13Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint8_13Input = { readonly sessionID: Endpoint8_13Request["params"]["sessionID"] }
const Endpoint8_13 = (raw: RawClient["server.session"]) => (input: Endpoint8_13Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_14Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint8_14Input = { readonly sessionID: Endpoint8_14Request["params"]["sessionID"] }
const Endpoint8_14 = (raw: RawClient["server.session"]) => (input: Endpoint8_14Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_15Request = Parameters<RawClient["server.session"]["session.todo"]>[0]
type Endpoint8_15Input = { readonly sessionID: Endpoint8_15Request["params"]["sessionID"] }
const Endpoint8_15 = (raw: RawClient["server.session"]) => (input: Endpoint8_15Input) =>
  raw["session.todo"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_16Request = Parameters<RawClient["server.session"]["session.rename"]>[0]
type Endpoint8_16Input = {
  readonly sessionID: Endpoint8_16Request["params"]["sessionID"]
  readonly title: Endpoint8_16Request["payload"]["title"]
}
const Endpoint8_16 = (raw: RawClient["server.session"]) => (input: Endpoint8_16Input) =>
  raw["session.rename"]({ params: { sessionID: input["sessionID"] }, payload: { title: input["title"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint8_17Request = Parameters<RawClient["server.session"]["session.archive"]>[0]
type Endpoint8_17Input = {
  readonly sessionID: Endpoint8_17Request["params"]["sessionID"]
  readonly archived: Endpoint8_17Request["payload"]["archived"]
}
const Endpoint8_17 = (raw: RawClient["server.session"]) => (input: Endpoint8_17Input) =>
  raw["session.archive"]({ params: { sessionID: input["sessionID"] }, payload: { archived: input["archived"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint8_18Request = Parameters<RawClient["server.session"]["session.remove"]>[0]
type Endpoint8_18Input = { readonly sessionID: Endpoint8_18Request["params"]["sessionID"] }
const Endpoint8_18 = (raw: RawClient["server.session"]) => (input: Endpoint8_18Input) =>
  raw["session.remove"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_19Request = Parameters<RawClient["server.session"]["session.command"]>[0]
type Endpoint8_19Input = {
  readonly sessionID: Endpoint8_19Request["params"]["sessionID"]
  readonly command: Endpoint8_19Request["payload"]["command"]
  readonly arguments: Endpoint8_19Request["payload"]["arguments"]
  readonly resume?: Endpoint8_19Request["payload"]["resume"]
}
const Endpoint8_19 = (raw: RawClient["server.session"]) => (input: Endpoint8_19Input) =>
  raw["session.command"]({
    params: { sessionID: input["sessionID"] },
    payload: { command: input["command"], arguments: input["arguments"], resume: input["resume"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_20Request = Parameters<RawClient["server.session"]["session.fork"]>[0]
type Endpoint8_20Input = {
  readonly sessionID: Endpoint8_20Request["params"]["sessionID"]
  readonly messageID?: Endpoint8_20Request["payload"]["messageID"]
}
const Endpoint8_20 = (raw: RawClient["server.session"]) => (input: Endpoint8_20Input) =>
  raw["session.fork"]({ params: { sessionID: input["sessionID"] }, payload: { messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_21Request = Parameters<RawClient["server.session"]["session.diff"]>[0]
type Endpoint8_21Input = {
  readonly sessionID: Endpoint8_21Request["params"]["sessionID"]
  readonly messageID?: Endpoint8_21Request["query"]["messageID"]
}
const Endpoint8_21 = (raw: RawClient["server.session"]) => (input: Endpoint8_21Input) =>
  raw["session.diff"]({ params: { sessionID: input["sessionID"] }, query: { messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_22Request = Parameters<RawClient["server.session"]["session.status"]>[0]
type Endpoint8_22Input = { readonly sessionID: Endpoint8_22Request["params"]["sessionID"] }
const Endpoint8_22 = (raw: RawClient["server.session"]) => (input: Endpoint8_22Input) =>
  raw["session.status"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_23Request = Parameters<RawClient["server.session"]["session.children"]>[0]
type Endpoint8_23Input = { readonly sessionID: Endpoint8_23Request["params"]["sessionID"] }
const Endpoint8_23 = (raw: RawClient["server.session"]) => (input: Endpoint8_23Input) =>
  raw["session.children"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint8_24Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint8_24Input = {
  readonly sessionID: Endpoint8_24Request["params"]["sessionID"]
  readonly limit?: Endpoint8_24Request["query"]["limit"]
  readonly after?: Endpoint8_24Request["query"]["after"]
}
const Endpoint8_24 = (raw: RawClient["server.session"]) => (input: Endpoint8_24Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_25Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint8_25Input = {
  readonly sessionID: Endpoint8_25Request["params"]["sessionID"]
  readonly after?: Endpoint8_25Request["query"]["after"]
}
const Endpoint8_25 = (raw: RawClient["server.session"]) => (input: Endpoint8_25Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint8_26Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint8_26Input = { readonly sessionID: Endpoint8_26Request["params"]["sessionID"] }
const Endpoint8_26 = (raw: RawClient["server.session"]) => (input: Endpoint8_26Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_27Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint8_27Input = {
  readonly sessionID: Endpoint8_27Request["params"]["sessionID"]
  readonly messageID: Endpoint8_27Request["params"]["messageID"]
}
const Endpoint8_27 = (raw: RawClient["server.session"]) => (input: Endpoint8_27Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup8 = (raw: RawClient["server.session"]) => ({
  list: Endpoint8_0(raw),
  create: Endpoint8_1(raw),
  active: Endpoint8_2(raw),
  get: Endpoint8_3(raw),
  switchAgent: Endpoint8_4(raw),
  switchModel: Endpoint8_5(raw),
  prompt: Endpoint8_6(raw),
  skill: Endpoint8_7(raw),
  shell: Endpoint8_8(raw),
  compact: Endpoint8_9(raw),
  wait: Endpoint8_10(raw),
  stage: Endpoint8_11(raw),
  clear: Endpoint8_12(raw),
  commit: Endpoint8_13(raw),
  context: Endpoint8_14(raw),
  todo: Endpoint8_15(raw),
  rename: Endpoint8_16(raw),
  archive: Endpoint8_17(raw),
  remove: Endpoint8_18(raw),
  command: Endpoint8_19(raw),
  fork: Endpoint8_20(raw),
  diff: Endpoint8_21(raw),
  status: Endpoint8_22(raw),
  children: Endpoint8_23(raw),
  history: Endpoint8_24(raw),
  events: Endpoint8_25(raw),
  interrupt: Endpoint8_26(raw),
  message: Endpoint8_27(raw),
})

type Endpoint9_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint9_0Input = {
  readonly sessionID: Endpoint9_0Request["params"]["sessionID"]
  readonly limit?: Endpoint9_0Request["query"]["limit"]
  readonly order?: Endpoint9_0Request["query"]["order"]
  readonly cursor?: Endpoint9_0Request["query"]["cursor"]
}
const Endpoint9_0 = (raw: RawClient["server.message"]) => (input: Endpoint9_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup9 = (raw: RawClient["server.message"]) => ({ list: Endpoint9_0(raw) })

type Endpoint10_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
const Endpoint10_0 = (raw: RawClient["server.model"]) => (input?: Endpoint10_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_1Request = Parameters<RawClient["server.model"]["model.default"]>[0]
type Endpoint10_1Input = { readonly location?: Endpoint10_1Request["query"]["location"] }
const Endpoint10_1 = (raw: RawClient["server.model"]) => (input?: Endpoint10_1Input) =>
  raw["model.default"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup10 = (raw: RawClient["server.model"]) => ({ list: Endpoint10_0(raw), default: Endpoint10_1(raw) })

type Endpoint11_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint11_0Input = { readonly location?: Endpoint11_0Request["query"]["location"] }
const Endpoint11_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint11_0Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint11_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint11_1Input = {
  readonly providerID: Endpoint11_1Request["params"]["providerID"]
  readonly location?: Endpoint11_1Request["query"]["location"]
}
const Endpoint11_1 = (raw: RawClient["server.provider"]) => (input: Endpoint11_1Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup11 = (raw: RawClient["server.provider"]) => ({ list: Endpoint11_0(raw), get: Endpoint11_1(raw) })

type Endpoint12_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
const Endpoint12_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint12_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint12_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint12_1Input = {
  readonly integrationID: Endpoint12_1Request["params"]["integrationID"]
  readonly location?: Endpoint12_1Request["query"]["location"]
}
const Endpoint12_1 = (raw: RawClient["server.integration"]) => (input: Endpoint12_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint12_2Input = {
  readonly integrationID: Endpoint12_2Request["params"]["integrationID"]
  readonly location?: Endpoint12_2Request["query"]["location"]
  readonly key: Endpoint12_2Request["payload"]["key"]
  readonly label?: Endpoint12_2Request["payload"]["label"]
}
const Endpoint12_2 = (raw: RawClient["server.integration"]) => (input: Endpoint12_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint12_3Input = {
  readonly integrationID: Endpoint12_3Request["params"]["integrationID"]
  readonly location?: Endpoint12_3Request["query"]["location"]
  readonly methodID: Endpoint12_3Request["payload"]["methodID"]
  readonly inputs: Endpoint12_3Request["payload"]["inputs"]
  readonly label?: Endpoint12_3Request["payload"]["label"]
}
const Endpoint12_3 = (raw: RawClient["server.integration"]) => (input: Endpoint12_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint12_4Input = {
  readonly attemptID: Endpoint12_4Request["params"]["attemptID"]
  readonly location?: Endpoint12_4Request["query"]["location"]
}
const Endpoint12_4 = (raw: RawClient["server.integration"]) => (input: Endpoint12_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint12_5Input = {
  readonly attemptID: Endpoint12_5Request["params"]["attemptID"]
  readonly location?: Endpoint12_5Request["query"]["location"]
  readonly code?: Endpoint12_5Request["payload"]["code"]
}
const Endpoint12_5 = (raw: RawClient["server.integration"]) => (input: Endpoint12_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint12_6Input = {
  readonly attemptID: Endpoint12_6Request["params"]["attemptID"]
  readonly location?: Endpoint12_6Request["query"]["location"]
}
const Endpoint12_6 = (raw: RawClient["server.integration"]) => (input: Endpoint12_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup12 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint12_0(raw),
  get: Endpoint12_1(raw),
  connectKey: Endpoint12_2(raw),
  connectOauth: Endpoint12_3(raw),
  attemptStatus: Endpoint12_4(raw),
  attemptComplete: Endpoint12_5(raw),
  attemptCancel: Endpoint12_6(raw),
})

type Endpoint13_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint13_0Input = {
  readonly credentialID: Endpoint13_0Request["params"]["credentialID"]
  readonly location?: Endpoint13_0Request["query"]["location"]
  readonly label: Endpoint13_0Request["payload"]["label"]
}
const Endpoint13_0 = (raw: RawClient["server.credential"]) => (input: Endpoint13_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint13_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint13_1Input = {
  readonly credentialID: Endpoint13_1Request["params"]["credentialID"]
  readonly location?: Endpoint13_1Request["query"]["location"]
}
const Endpoint13_1 = (raw: RawClient["server.credential"]) => (input: Endpoint13_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup13 = (raw: RawClient["server.credential"]) => ({ update: Endpoint13_0(raw), remove: Endpoint13_1(raw) })

type Endpoint14_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint14_0Input = { readonly location?: Endpoint14_0Request["query"]["location"] }
const Endpoint14_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint14_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint14_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint14_1Input = { readonly projectID?: Endpoint14_1Request["query"]["projectID"] }
const Endpoint14_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint14_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint14_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint14_2Input = { readonly id: Endpoint14_2Request["params"]["id"] }
const Endpoint14_2 = (raw: RawClient["server.permission"]) => (input: Endpoint14_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint14_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint14_3Input = {
  readonly sessionID: Endpoint14_3Request["params"]["sessionID"]
  readonly id?: Endpoint14_3Request["payload"]["id"]
  readonly action: Endpoint14_3Request["payload"]["action"]
  readonly resources: Endpoint14_3Request["payload"]["resources"]
  readonly save?: Endpoint14_3Request["payload"]["save"]
  readonly metadata?: Endpoint14_3Request["payload"]["metadata"]
  readonly source?: Endpoint14_3Request["payload"]["source"]
  readonly agent?: Endpoint14_3Request["payload"]["agent"]
}
const Endpoint14_3 = (raw: RawClient["server.permission"]) => (input: Endpoint14_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint14_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint14_4Input = { readonly sessionID: Endpoint14_4Request["params"]["sessionID"] }
const Endpoint14_4 = (raw: RawClient["server.permission"]) => (input: Endpoint14_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint14_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint14_5Input = {
  readonly sessionID: Endpoint14_5Request["params"]["sessionID"]
  readonly requestID: Endpoint14_5Request["params"]["requestID"]
}
const Endpoint14_5 = (raw: RawClient["server.permission"]) => (input: Endpoint14_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint14_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint14_6Input = {
  readonly sessionID: Endpoint14_6Request["params"]["sessionID"]
  readonly requestID: Endpoint14_6Request["params"]["requestID"]
  readonly reply: Endpoint14_6Request["payload"]["reply"]
  readonly message?: Endpoint14_6Request["payload"]["message"]
}
const Endpoint14_6 = (raw: RawClient["server.permission"]) => (input: Endpoint14_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup14 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint14_0(raw),
  listSaved: Endpoint14_1(raw),
  removeSaved: Endpoint14_2(raw),
  create: Endpoint14_3(raw),
  list: Endpoint14_4(raw),
  get: Endpoint14_5(raw),
  reply: Endpoint14_6(raw),
})

type Endpoint15_0Request = Parameters<RawClient["server.fs"]["fs.content"]>[0]
type Endpoint15_0Input = {
  readonly location?: Endpoint15_0Request["query"]["location"]
  readonly path: Endpoint15_0Request["query"]["path"]
}
const Endpoint15_0 = (raw: RawClient["server.fs"]) => (input: Endpoint15_0Input) =>
  raw["fs.content"]({ query: { location: input["location"], path: input["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint15_1Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint15_1Input = {
  readonly location?: Endpoint15_1Request["query"]["location"]
  readonly path?: Endpoint15_1Request["query"]["path"]
}
const Endpoint15_1 = (raw: RawClient["server.fs"]) => (input?: Endpoint15_1Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint15_2Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint15_2Input = {
  readonly location?: Endpoint15_2Request["query"]["location"]
  readonly query: Endpoint15_2Request["query"]["query"]
  readonly type?: Endpoint15_2Request["query"]["type"]
  readonly limit?: Endpoint15_2Request["query"]["limit"]
}
const Endpoint15_2 = (raw: RawClient["server.fs"]) => (input: Endpoint15_2Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup15 = (raw: RawClient["server.fs"]) => ({
  content: Endpoint15_0(raw),
  list: Endpoint15_1(raw),
  find: Endpoint15_2(raw),
})

type Endpoint16_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint16_0Input = { readonly location?: Endpoint16_0Request["query"]["location"] }
const Endpoint16_0 = (raw: RawClient["server.command"]) => (input?: Endpoint16_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup16 = (raw: RawClient["server.command"]) => ({ list: Endpoint16_0(raw) })

type Endpoint17_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint17_0Input = { readonly location?: Endpoint17_0Request["query"]["location"] }
const Endpoint17_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint17_0Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup17 = (raw: RawClient["server.skill"]) => ({ list: Endpoint17_0(raw) })

const Endpoint18_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup18 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint18_0(raw) })

type Endpoint19_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint19_0Input = { readonly location?: Endpoint19_0Request["query"]["location"] }
const Endpoint19_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint19_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint19_1Input = {
  readonly location?: Endpoint19_1Request["query"]["location"]
  readonly command?: Endpoint19_1Request["payload"]["command"]
  readonly args?: Endpoint19_1Request["payload"]["args"]
  readonly cwd?: Endpoint19_1Request["payload"]["cwd"]
  readonly title?: Endpoint19_1Request["payload"]["title"]
  readonly env?: Endpoint19_1Request["payload"]["env"]
}
const Endpoint19_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint19_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint19_2Input = {
  readonly ptyID: Endpoint19_2Request["params"]["ptyID"]
  readonly location?: Endpoint19_2Request["query"]["location"]
}
const Endpoint19_2 = (raw: RawClient["server.pty"]) => (input: Endpoint19_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint19_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint19_3Input = {
  readonly ptyID: Endpoint19_3Request["params"]["ptyID"]
  readonly location?: Endpoint19_3Request["query"]["location"]
  readonly title?: Endpoint19_3Request["payload"]["title"]
  readonly size?: Endpoint19_3Request["payload"]["size"]
}
const Endpoint19_3 = (raw: RawClient["server.pty"]) => (input: Endpoint19_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint19_4Input = {
  readonly ptyID: Endpoint19_4Request["params"]["ptyID"]
  readonly location?: Endpoint19_4Request["query"]["location"]
}
const Endpoint19_4 = (raw: RawClient["server.pty"]) => (input: Endpoint19_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup19 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint19_0(raw),
  create: Endpoint19_1(raw),
  get: Endpoint19_2(raw),
  update: Endpoint19_3(raw),
  remove: Endpoint19_4(raw),
})

type Endpoint20_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint20_0Input = { readonly location?: Endpoint20_0Request["query"]["location"] }
const Endpoint20_0 = (raw: RawClient["server.question"]) => (input?: Endpoint20_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint20_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint20_1Input = { readonly sessionID: Endpoint20_1Request["params"]["sessionID"] }
const Endpoint20_1 = (raw: RawClient["server.question"]) => (input: Endpoint20_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint20_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint20_2Input = {
  readonly sessionID: Endpoint20_2Request["params"]["sessionID"]
  readonly requestID: Endpoint20_2Request["params"]["requestID"]
  readonly answers: Endpoint20_2Request["payload"]["answers"]
}
const Endpoint20_2 = (raw: RawClient["server.question"]) => (input: Endpoint20_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint20_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint20_3Input = {
  readonly sessionID: Endpoint20_3Request["params"]["sessionID"]
  readonly requestID: Endpoint20_3Request["params"]["requestID"]
}
const Endpoint20_3 = (raw: RawClient["server.question"]) => (input: Endpoint20_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup20 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint20_0(raw),
  list: Endpoint20_1(raw),
  reply: Endpoint20_2(raw),
  reject: Endpoint20_3(raw),
})

type Endpoint21_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint21_0Input = { readonly location?: Endpoint21_0Request["query"]["location"] }
const Endpoint21_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint21_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup21 = (raw: RawClient["server.reference"]) => ({ list: Endpoint21_0(raw) })

type Endpoint22_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint22_0Input = {
  readonly projectID: Endpoint22_0Request["params"]["projectID"]
  readonly location?: Endpoint22_0Request["query"]["location"]
  readonly strategy: Endpoint22_0Request["payload"]["strategy"]
  readonly directory: Endpoint22_0Request["payload"]["directory"]
  readonly name?: Endpoint22_0Request["payload"]["name"]
}
const Endpoint22_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint22_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint22_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint22_1Input = {
  readonly projectID: Endpoint22_1Request["params"]["projectID"]
  readonly location?: Endpoint22_1Request["query"]["location"]
  readonly directory: Endpoint22_1Request["payload"]["directory"]
  readonly force: Endpoint22_1Request["payload"]["force"]
}
const Endpoint22_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint22_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint22_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint22_2Input = {
  readonly projectID: Endpoint22_2Request["params"]["projectID"]
  readonly location?: Endpoint22_2Request["query"]["location"]
}
const Endpoint22_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint22_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup22 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint22_0(raw),
  remove: Endpoint22_1(raw),
  refresh: Endpoint22_2(raw),
})

type Endpoint23_0Request = Parameters<RawClient["server.project"]["project.current"]>[0]
type Endpoint23_0Input = { readonly location?: Endpoint23_0Request["query"]["location"] }
const Endpoint23_0 = (raw: RawClient["server.project"]) => (input?: Endpoint23_0Input) =>
  raw["project.current"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint23_1Request = Parameters<RawClient["server.project"]["project.directories"]>[0]
type Endpoint23_1Input = {
  readonly projectID: Endpoint23_1Request["params"]["projectID"]
  readonly location?: Endpoint23_1Request["query"]["location"]
}
const Endpoint23_1 = (raw: RawClient["server.project"]) => (input: Endpoint23_1Input) =>
  raw["project.directories"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup23 = (raw: RawClient["server.project"]) => ({
  current: Endpoint23_0(raw),
  directories: Endpoint23_1(raw),
})

type Endpoint24_0Request = Parameters<RawClient["server.vcs"]["vcs.get"]>[0]
type Endpoint24_0Input = { readonly location?: Endpoint24_0Request["query"]["location"] }
const Endpoint24_0 = (raw: RawClient["server.vcs"]) => (input?: Endpoint24_0Input) =>
  raw["vcs.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint24_1Request = Parameters<RawClient["server.vcs"]["vcs.status"]>[0]
type Endpoint24_1Input = { readonly location?: Endpoint24_1Request["query"]["location"] }
const Endpoint24_1 = (raw: RawClient["server.vcs"]) => (input?: Endpoint24_1Input) =>
  raw["vcs.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup24 = (raw: RawClient["server.vcs"]) => ({ get: Endpoint24_0(raw), status: Endpoint24_1(raw) })

type Endpoint25_0Request = Parameters<RawClient["server.workspace"]["workspace.list"]>[0]
type Endpoint25_0Input = { readonly location?: Endpoint25_0Request["query"]["location"] }
const Endpoint25_0 = (raw: RawClient["server.workspace"]) => (input?: Endpoint25_0Input) =>
  raw["workspace.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_1Request = Parameters<RawClient["server.workspace"]["workspace.status"]>[0]
type Endpoint25_1Input = { readonly location?: Endpoint25_1Request["query"]["location"] }
const Endpoint25_1 = (raw: RawClient["server.workspace"]) => (input?: Endpoint25_1Input) =>
  raw["workspace.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_2Request = Parameters<RawClient["server.workspace"]["workspace.adapters"]>[0]
type Endpoint25_2Input = { readonly location?: Endpoint25_2Request["query"]["location"] }
const Endpoint25_2 = (raw: RawClient["server.workspace"]) => (input?: Endpoint25_2Input) =>
  raw["workspace.adapters"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_3Request = Parameters<RawClient["server.workspace"]["workspace.create"]>[0]
type Endpoint25_3Input = {
  readonly location?: Endpoint25_3Request["query"]["location"]
  readonly type: Endpoint25_3Request["payload"]["type"]
  readonly branch?: Endpoint25_3Request["payload"]["branch"]
  readonly extra?: Endpoint25_3Request["payload"]["extra"]
}
const Endpoint25_3 = (raw: RawClient["server.workspace"]) => (input: Endpoint25_3Input) =>
  raw["workspace.create"]({
    query: { location: input["location"] },
    payload: { type: input["type"], branch: input["branch"], extra: input["extra"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint25_4Request = Parameters<RawClient["server.workspace"]["workspace.syncList"]>[0]
type Endpoint25_4Input = { readonly location?: Endpoint25_4Request["query"]["location"] }
const Endpoint25_4 = (raw: RawClient["server.workspace"]) => (input?: Endpoint25_4Input) =>
  raw["workspace.syncList"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint25_5Request = Parameters<RawClient["server.workspace"]["workspace.warp"]>[0]
type Endpoint25_5Input = {
  readonly location?: Endpoint25_5Request["query"]["location"]
  readonly id: Endpoint25_5Request["payload"]["id"]
  readonly sessionID: Endpoint25_5Request["payload"]["sessionID"]
  readonly copyChanges?: Endpoint25_5Request["payload"]["copyChanges"]
}
const Endpoint25_5 = (raw: RawClient["server.workspace"]) => (input: Endpoint25_5Input) =>
  raw["workspace.warp"]({
    query: { location: input["location"] },
    payload: { id: input["id"], sessionID: input["sessionID"], copyChanges: input["copyChanges"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint25_6Request = Parameters<RawClient["server.workspace"]["workspace.remove"]>[0]
type Endpoint25_6Input = {
  readonly id: Endpoint25_6Request["params"]["id"]
  readonly location?: Endpoint25_6Request["query"]["location"]
}
const Endpoint25_6 = (raw: RawClient["server.workspace"]) => (input: Endpoint25_6Input) =>
  raw["workspace.remove"]({ params: { id: input["id"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup25 = (raw: RawClient["server.workspace"]) => ({
  list: Endpoint25_0(raw),
  status: Endpoint25_1(raw),
  adapters: Endpoint25_2(raw),
  create: Endpoint25_3(raw),
  syncList: Endpoint25_4(raw),
  warp: Endpoint25_5(raw),
  remove: Endpoint25_6(raw),
})

type Endpoint26_0Request = Parameters<RawClient["server.controlPlane"]["controlPlane.moveSession"]>[0]
type Endpoint26_0Input = {
  readonly location?: Endpoint26_0Request["query"]["location"]
  readonly sessionID: Endpoint26_0Request["payload"]["sessionID"]
  readonly destination: Endpoint26_0Request["payload"]["destination"]
  readonly moveChanges?: Endpoint26_0Request["payload"]["moveChanges"]
}
const Endpoint26_0 = (raw: RawClient["server.controlPlane"]) => (input: Endpoint26_0Input) =>
  raw["controlPlane.moveSession"]({
    query: { location: input["location"] },
    payload: { sessionID: input["sessionID"], destination: input["destination"], moveChanges: input["moveChanges"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup26 = (raw: RawClient["server.controlPlane"]) => ({ moveSession: Endpoint26_0(raw) })

const Endpoint27_0 = (raw: RawClient["server.remote"]) => () =>
  raw["remote.get"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint27_1Request = Parameters<RawClient["server.remote"]["remote.login.start"]>[0]
type Endpoint27_1Input = { readonly connector: Endpoint27_1Request["params"]["connector"] }
const Endpoint27_1 = (raw: RawClient["server.remote"]) => (input: Endpoint27_1Input) =>
  raw["remote.login.start"]({ params: { connector: input["connector"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint27_2Request = Parameters<RawClient["server.remote"]["remote.login.events"]>[0]
type Endpoint27_2Input = { readonly flow: Endpoint27_2Request["params"]["flow"] }
const Endpoint27_2 = (raw: RawClient["server.remote"]) => (input: Endpoint27_2Input) =>
  Stream.unwrap(
    raw["remote.login.events"]({ params: { flow: input["flow"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint27_3Request = Parameters<RawClient["server.remote"]["remote.login.input"]>[0]
type Endpoint27_3Input = {
  readonly flow: Endpoint27_3Request["params"]["flow"]
  readonly value: Endpoint27_3Request["payload"]["value"]
}
const Endpoint27_3 = (raw: RawClient["server.remote"]) => (input: Endpoint27_3Input) =>
  raw["remote.login.input"]({ params: { flow: input["flow"] }, payload: { value: input["value"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint27_4Request = Parameters<RawClient["server.remote"]["remote.login.cancel"]>[0]
type Endpoint27_4Input = { readonly flow: Endpoint27_4Request["params"]["flow"] }
const Endpoint27_4 = (raw: RawClient["server.remote"]) => (input: Endpoint27_4Input) =>
  raw["remote.login.cancel"]({ params: { flow: input["flow"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint27_5Request = Parameters<RawClient["server.remote"]["remote.account.remove"]>[0]
type Endpoint27_5Input = {
  readonly connector: Endpoint27_5Request["params"]["connector"]
  readonly account: Endpoint27_5Request["params"]["account"]
}
const Endpoint27_5 = (raw: RawClient["server.remote"]) => (input: Endpoint27_5Input) =>
  raw["remote.account.remove"]({ params: { connector: input["connector"], account: input["account"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint27_6Request = Parameters<RawClient["server.remote"]["remote.account.pair"]>[0]
type Endpoint27_6Input = {
  readonly connector: Endpoint27_6Request["params"]["connector"]
  readonly account: Endpoint27_6Request["params"]["account"]
}
const Endpoint27_6 = (raw: RawClient["server.remote"]) => (input: Endpoint27_6Input) =>
  raw["remote.account.pair"]({ params: { connector: input["connector"], account: input["account"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint27_7Request = Parameters<RawClient["server.remote"]["remote.account.test"]>[0]
type Endpoint27_7Input = {
  readonly connector: Endpoint27_7Request["params"]["connector"]
  readonly account: Endpoint27_7Request["params"]["account"]
}
const Endpoint27_7 = (raw: RawClient["server.remote"]) => (input: Endpoint27_7Input) =>
  raw["remote.account.test"]({ params: { connector: input["connector"], account: input["account"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup27 = (raw: RawClient["server.remote"]) => ({
  get: Endpoint27_0(raw),
  login: Endpoint27_1(raw),
  loginEvents: Endpoint27_2(raw),
  loginInput: Endpoint27_3(raw),
  loginCancel: Endpoint27_4(raw),
  remove: Endpoint27_5(raw),
  pair: Endpoint27_6(raw),
  test: Endpoint27_7(raw),
})

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  capabilities: adaptGroup1(raw["server.capabilities"]),
  formatters: adaptGroup2(raw["server.formatter"]),
  config: adaptGroup3(raw["server.config"]),
  lsp: adaptGroup4(raw["server.lsp"]),
  mcp: adaptGroup5(raw["server.mcp"]),
  location: adaptGroup6(raw["server.location"]),
  agents: adaptGroup7(raw["server.agent"]),
  sessions: adaptGroup8(raw["server.session"]),
  messages: adaptGroup9(raw["server.message"]),
  models: adaptGroup10(raw["server.model"]),
  providers: adaptGroup11(raw["server.provider"]),
  integrations: adaptGroup12(raw["server.integration"]),
  credentials: adaptGroup13(raw["server.credential"]),
  permissions: adaptGroup14(raw["server.permission"]),
  files: adaptGroup15(raw["server.fs"]),
  commands: adaptGroup16(raw["server.command"]),
  skills: adaptGroup17(raw["server.skill"]),
  events: adaptGroup18(raw["server.event"]),
  ptys: adaptGroup19(raw["server.pty"]),
  questions: adaptGroup20(raw["server.question"]),
  references: adaptGroup21(raw["server.reference"]),
  projectCopies: adaptGroup22(raw["server.projectCopy"]),
  projects: adaptGroup23(raw["server.project"]),
  vcs: adaptGroup24(raw["server.vcs"]),
  workspace: adaptGroup25(raw["server.workspace"]),
  controlPlane: adaptGroup26(raw["server.controlPlane"]),
  remote: adaptGroup27(raw["server.remote"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
